### ISSUE TITLE
'node_modules/.bin/jest' could not be spawned

### ISSUE THREAD

**Issue by zhukovka** [JosePedroDias/nuclide-test-runner-jest#6]
I have Jest locally installed in node modules 
```
$ ls node_modules/.bin
_mocha          jest            mocha           react-scripts
```

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [nuclide-test-runner-jest](git://github.com/JosePedroDias/nuclide-test-runner-jest) package 0.3.0

### Stack Trace

Uncaught SyntaxError: Unexpected end of JSON input

```
At file:///Applications/Atom.app/Contents/Resources/app/static/index.html:1

SyntaxError: Unexpected end of JSON input
  at Object.parse (native)
  at /packages/nuclide-test-runner-jest/JestTestRunner.js:134:25)
  at emitOne (events.js:101:20)
  at Socket.emit (events.js:188:7)
  at Pipe._handle.close [as _onclose] (net.js:493:12)

```

### Commands

```
  2x -9:34.7.0 nuclide-home:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling)
  2x -9:23.7.0 nuclide-test-runner:toggle-panel (input.hidden-input)
     -8:52.7.0 nuclide-debugger:continue-debugging (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -8:50.3.0 nuclide-console:toggle (button.inline-block.btn.icon.icon-sync.btn-sm.btn-primary)
     -7:51 core:copy (div.ReactVirtualized__Grid.ReactVirtualized__List)
     -6:24.5.0 autocomplete-plus:cancel (input.hidden-input)
     -6:24.1.0 core:save (input.hidden-input)
  2x -4:50.7.0 nuclide-test-runner:toggle-panel (input.hidden-input)
     -4:42.8.0 core:copy (atom-notification.error.icon.icon-flame.native-key-bindings.has-close)
  2x -4:19.3.0 core:undo (atom-pane.pane)
     -4:14.4.0 core:redo (input.hidden-input)
  2x -4:13.5.0 core:save (input.hidden-input)
     -2:18.7.0 nuclide-debugger:continue-debugging (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:13.6.0 nuclide-test-runner:toggle-panel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-typescript 11.0.6 
busy-signal 1.4.3 
eclipse-keybindings 0.9.0 
emmet 2.4.3 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
intentions 1.1.2 
language-babel 2.67.0 
language-graphql 0.9.0 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.11 
language-swift 0.5.0 
language-thrift 1.0.2 
linter 2.2.0 
linter-ui-default 1.6.2 
MagicPython 1.0.10 
merge-conflicts 1.4.5 
nuclide 0.239.0 
nuclide-format-js 0.0.36 
nuclide-test-runner-jest 0.3.0 
nuclide-test-runner-mocha 0.1.1 
open-in-browser 0.5.2 
platformio-ide-terminal 2.5.3 
set-syntax 0.3.2 
sort-lines 0.14.0 
tool-bar 1.1.0 
```

**Comment by JosePedroDias** [comment]
Thank you for the report. I'm unpublishing the package because I'm no longer maintaining it (I'm not even using atom any longer, switched to visual studio code and jest -w)
